fragment Statistic on Statistic {
  id
  nftTransferTotal
  nftPayTotal
  nftBurnTotal
  nftTotal
  marketSaleTotal
  marketSaleNearSum
  marketSaleNearTotal
  marketRentTotal
  marketRentNearSum
  marketRentNearTotal
  accountTotal
}
